### ISSUE TITLE
Inconsistency in the sign of "p" in density structure

### ISSUE THREAD

**Issue by baibhavsrivastava** [keflavich/radmc3dPy#1]
The documentation mentions that the exponential power law exponent for density is "2+p":
![image](https://user-images.githubusercontent.com/66297621/226186627-351efd71-a11c-4b7e-b214-482c63bcf720.png)
But in the ppdisk module (line 241), the parameter 'plsig' takes in the opposite sign (2 - plsig):
![image](https://user-images.githubusercontent.com/66297621/226186759-5330e694-4805-4305-aa0b-4521910e0211.png)
This leads to an inconsistency in the density structure if the user follows the documentation and does not check the code.

**Comment by keflavich** [comment]
Thanks for the correction.  I'd welcome a pull request to fix it.

Note that this code is by Attila Juhasz, forked from bitbucket: https://bitbucket.org/at_juhasz/radmc3dpy/src/master/.  That version might be more up to date

**Comment by baibhavsrivastava** [comment]
Thanks a lot for pointing out to the code by Attila Juhasz, I checked it out and saw the same inconsistency there. Will raise an issue there too. For now, I have opened a pull request for this one.

**Comment by baibhavsrivastava** [comment]
I am extremely sorry for the delay. I have opened up a pull request after making necessary changes. I would be glad if you could review them.

Also, I tried to raise an issue on the original code at bitbucket but it seems like I do not have permission to raise an issue there, neither can I contact the author. Do you have any suggestions as to how can this be tackled?

**Comment by keflavich** [comment]
No idea, sorry!  I'll merge your suggested change though.

**Comment by baibhavsrivastava** [comment]
Thanks a lot.
